// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.00m,
                            Description = "Discount on iPhone 15 purchase.",
                            ProductName = "Apple iPhone 15"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 120.00m,
                            Description = "Save on Samsung Galaxy S24.",
                            ProductName = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50.00m,
                            Description = "Noise-canceling headphones discount.",
                            ProductName = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 200.00m,
                            Description = "Exclusive Dell XPS 15 discount.",
                            ProductName = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 180.00m,
                            Description = "Special discount on MacBook Air M3.",
                            ProductName = "Apple MacBook Air M3"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 20.00m,
                            Description = "Save on premium Logitech mouse.",
                            ProductName = "Logitech MX Master 3S"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 250.00m,
                            Description = "Graphics card discount offer.",
                            ProductName = "Asus ROG Strix RTX 4080"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 175.00m,
                            Description = "Camera purchase discount.",
                            ProductName = "Canon EOS R7"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 15.00m,
                            Description = "Discount on smart speaker.",
                            ProductName = "Amazon Echo Dot (5th Gen)"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 30.00m,
                            Description = "Fitness tracker discount.",
                            ProductName = "Fitbit Charge 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
